//
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//


WARNING: this project is moving over Apache Geronimo umbrella project, new source repository is available at https://gitbox.apache.org/repos/asf?p=geronimo-batchee.git and
website should follow at https://geronimo.apache.org/batchee/.

= Apache JBatch
Apache BatchEE is a project providing an implementation of JBatch (aka jsr-352) and a set of useful extension for this specification.

The JBatch implementation is based on a fork of the Reference Implementation provided by IBM but it has now a set of enhancements.

== Get started

To learn more about BatchEE you can visit its http://batchee.incubator.apache.org/modules.html[modules page].

If you want to learn about JBatch extensions please visit our http://batchee.incubator.apache.org/extensions.html[extensions page].

If you are more interested in a GUI solution, have a look at our http://batchee.incubator.apache.org/gui.html[gui] page.

Finally if you want to control your batches from Maven just open the maven plugin page.
